services:
  ai-voice-chat:
    build: .
    env_file:
      - .env
    ports:
      - "9078:9078"
    volumes:
      - .:/app
      # หากต้องการ mount credentials
      # - ./credentials.json:/app/credentials.json
    restart: unless-stopped
