name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted # ใช้ Self-hosted Runner ที่ติดตั้งอยู่ใน VPN
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # ใช้ action เพื่อ checkout โค้ดจาก GitHub

      # ใช้สคริปต์ VPN ที่มีอยู่ (ไม่ต้อง sudo)
      - name: Connect to VPN
        env:
          VPN_USERNAME: ${{ secrets.VPN_USER }}
          VPN_PASSWORD: ${{ secrets.VPN_PASSWORD }}
          VPN_BUU: ${{ secrets.VPN_BUU }} # ตรวจสอบชื่อตัวแปรให้ตรงกับในสคริปต์
        run: |
          cd ~
          chmod +x ./vpn-connect.sh  # เพิ่มบรรทัดนี้
          ./vpn-connect.sh
          sleep 5 # รอให้ VPN เชื่อมต่อ

      # Test deploy
      # ดึงโค้ดและ deploy
      - name: Pull and deploy
        run: |
          cd ~/AI-Voice-Chat
          git pull origin main # เปลี่ยน branch ตามต้องการ

          # ใช้ full path ของ docker-compose
          ~/bin/docker-compose down
          ~/bin/docker-compose up -d --build
