name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted # ใช้ Self-hosted Runner ที่ติดตั้งอยู่ใน VPN
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # ใช้ action เพื่อ checkout โค้ดจาก GitHub

      # set git pull
      - name: Set up git to allow pulling
        run: |
          cd ~/AI-Voice-Chat
          git pull

      - name: Stop and Remove old containers (if any)
        run: |
          cd ~/AI-Voice-Chat
          # ใช้ if condition เพื่อให้แน่ใจว่ามี container รันอยู่ก่อนจะ down
          if docker compose ps -q | grep -q .; then
            docker compose down
          fi

      - name: Build and Start new containers
        run: |
          cd ~/AI-Voice-Chat
          docker compose up -d --build
        # --remove-orphans # --remove-orphans เพื่อลบ container ที่ไม่ได้อยู่ใน compose file ออกไป
